### ISSUE TITLE
errors with raster-dev

### ISSUE THREAD

**Issue by rhijmans** [dfriend21/quadtree#20]
When checking quadtree with the dev version of "raster" (https://github.com/rspatial/raster) I now get

```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test_minor_functions.R:151:3'): projection() runs without errors and returns correct value ──
  `qt_proj` (`actual`) not equal to raster::projection(habitat) (`expected`).
  
  `actual`:   ""
  `expected`: NA
  ```

This is because of changes in "raster" related to the changes in the "sp family" packages. sp::identicalCRS does not work well with Raster* objects anymore. 

You now need to use CRS(Raster*) or you could use terra::same.crs(x, y). But the best approach might be to use "terra" instead of "raster".

Can you please fix this so that your package won't break when I submit "raster" to CRAN?

**Comment by dfriend21** [comment]
Thanks for the notification. This should already be taken care of in the development version, as `quadtree` was recently updated to use `terra` instead of `raster` - I just haven't pushed that version to CRAN yet. I'll get the most recent version submitted.

**Comment by rhijmans** [comment]
Thanks!

**Comment by brownag** [comment]
hey @dfriend21 I see the prior version (0.1.10) fell off CRAN. please let me know if I can be of any assistance on a re-submission

**Comment by dfriend21** [comment]
@brownag Thanks for the offer - finally got it submitted to CRAN today, so hopefully it'll be back up in the near future.
