### ISSUE TITLE
Make 'quadtree' compatible with 'terra'

### ISSUE THREAD

**Issue by dfriend21** [dfriend21/quadtree#7]
Eventually I'll want to modify the code to accept `SpatRaster` objects from `terra`.

**Comment by dylanbeaudette** [comment]
Any progress on this front? Thanks again for the awesome package.

**Comment by dfriend21** [comment]
A simple conversion from `RasterLayer` to `SpatRaster` was added in #16. I'll close this for now, as this at least lets `SpatRaster` be accepted by `quadtree()`, but added a new issue (#18) for a full conversion of all functionality from `raster` to `terra`.
